Add spark-hyperloglog to Mozilla
mozilla/spark-hyperloglog pull request #1
Opened 2017-07-14 03:56 UTC by fbertsch

This also adds the changes I made for Quantum RC, as well as updates some tests. I bumped the version to 2.0.0 since the API has changed. We can release this on spark-packages under the mozilla name and it will be separate from vitillo/spark-hyperloglog.

2017-07-14 03:58 UTC, fbertsch commented
I wanted to change the license to MPL 2.0 but I don't think we can switch it from Apache.

2017-07-17 15:02 UTC, mreid-moz requested changes

2017-07-17 15:02 UTC, mreid-moz commented on src/main/scala/com/mozilla/spark/sql/hyperloglog/aggregates/HyperLogLogMerge.scala
> +   * This HLL instance is has zero counts.
grammar nit: "is has"?

2017-07-17 15:02 UTC, mreid-moz commented on src/main/scala/com/mozilla/spark/sql/hyperloglog/aggregates/HyperLogLogMerge.scala
> +      if (buffer(0) != null) {
This block (`if (buffer(0 != null)...`) is repeated in the parent`HyperLogLogMerge` update function as well - can we extract the common chunk to a separate function?

2017-07-17 15:02 UTC, mreid-moz commented on src/main/scala/com/mozilla/spark/sql/hyperloglog/aggregates/HyperLogLogMerge.scala
> +  val emptyHll = new DenseHLL(12, new Bytes(Array.fill[Byte](1 << 12)(0)))
Can we factor out `12` as a constant named to indicate that it is the default HLL bits?

2017-07-17 15:02 UTC, mreid-moz commented on src/main/scala/com/mozilla/spark/sql/hyperloglog/functions/package.scala
> +      case v: String =>
`x` is defined as a String param - I don't think we need to include the type here. This could be simplified to `case _`, I think.

2017-07-17 15:02 UTC, mreid-moz commented on src/test/scala/com/mozilla/spark/sql/hyperloglog/test/HyperLogLog.scala
> +    spark.udf.register("hll_cardinality", hllCardinality _)
Can you register these UDFs once in a setup function rather than within each test?

2017-07-17 20:40 UTC, fbertsch commented
@mreid-moz RFAL

2017-07-18 12:36 UTC, mreid-moz approved these changes
Looks good, thanks!

2017-07-18 12:39 UTC, merged